tap "getantibody/tap"
tap "heroku/brew"
tap "homebrew/apache"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "mongodb/brew"
tap "wagoodman/dive"
brew "bash"
brew "bash-completion"
brew "python"
brew "coreutils"
brew "findutils", args: ["with-default-names"]
brew "git"
brew "diff-so-fancy"
brew "asciinema"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "go"
brew "grep"
brew "less"
brew "mas"
brew "maven"
brew "mongodb"
brew "node@8"
brew "nvm"
brew "openssl"
brew "protobuf"
brew "rsync"
brew "sbt"
brew "scala"
brew "vim"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "openshift-cli"
brew "zsh"
brew "getantibody/tap/antibody"
brew "heroku/brew/heroku"
brew "wagoodman/dive/dive"
cask "cheatsheet"
cask "dropbox"
cask "firefox"
cask "google-chrome-canary"
cask "hipchat"
cask "iterm2"
cask "java11"
cask "jetbrains-toolbox"
cask "openoffice"
cask "postman"
cask "slack"
cask "spectacle"
cask "sublime-text"
cask "vlc"
cask "tunnelblick"
mas "Be Focused", id: 973134470
mas "GIPHY CAPTURE", id: 668208984
mas "Numbers", id: 409203825
mas "Wunderlist", id: 410628904
mas "Pages", id: 409201541
mas "HazeOver", id: 430798174
